# Generated by Django 4.2.7 on 2023-12-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('country_of_benchmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_started.country')),
                ('region_of_benchmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_started.region')),
            ],
        ),
    ]
